server {
    listen 80;
    server_name andiesmiki.hu;
    location /.well-known/acme-challenge/ { root /var/www/certbot; }
    location / { return 301 https://andiesmiki.hu$request_uri; }
}

server {
    listen 80;
    server_name www.andiesmiki.hu;
    location /.well-known/acme-challenge/ { root /var/www/certbot; }
    location / { return 301 https://andiesmiki.hu$request_uri; }
}

server {
    listen 443 ssl;
    server_name www.andiesmiki.hu;
    ssl_certificate /etc/letsencrypt/live/andiesmiki.hu/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/andiesmiki.hu/privkey.pem;
    return 301 https://andiesmiki.hu$request_uri;
}

server {
    listen 443 ssl;
    server_name andiesmiki.hu;
    ssl_certificate /etc/letsencrypt/live/andiesmiki.hu/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/andiesmiki.hu/privkey.pem;
    root /var/www/andiesmiki.hu;
    index index.html;
    location / { try_files $uri $uri/ $uri/index.html =404; }
}
